app/weddingwrangle/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from . import views
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

app_name = "weddingwrangle"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("guests/", views.GuestList.as_view(), name="guest_list"),
    path("guests/create/", views.GuestCreate.as_view(), name="guest_create"),
    path("guests/export/csv/", views.export_csv, name="guest_export_csv"),
    path("guests/export/qr/", views.export_qr, name="guest_export_qr"),
    path("guests/upload/", views.GuestUpload.as_view(), name="guest_upload"),
    path(
        "guests/<int:pk>/update/",
        views.GuestUpdate.as_view(success_url=reverse_lazy("guest_list")),
        name="guest_update",
    ),
    path("guests/<int:pk>/delete/", views.GuestDelete.as_view(), name="guest_delete"),
    path("email/", views.EmailList.as_view(), name="email_create"),
    path(
        "email/rsvp_template/",
        views.RSVPEmailTemplate.as_view(
            success_url=reverse_lazy("email_create"),
        ),
        name="rsvp_email_template",
    ),
    path(
        "email/<int:pk>/email_confirm/",
        views.EmailConfirm.as_view(
            success_url=reverse_lazy("email_create"),
        ),
        name="email_confirm",
    ),
    path("email/<int:pk>/detail/", views.EmailDetail.as_view(), name="email_detail"),
    path("qr_code/", include("qr_code.urls", namespace="qr_code"), name="qr_urls"),
    path(
        "rsvp/thankyou/",
        TemplateView.as_view(template_name="weddingwrangle/rsvp_thank_partner.html"),
        name="rsvp_thank_partner",
    ),
    path(
        "rsvp/<str:rsvp_link>/",
        views.RSVPView.as_view(success_url=reverse_lazy("rsvp_thank")),
        name="rsvp",
    ),
    path(
        "rsvp/<str:rsvp_link>/thanks/",
        views.RSVPThank.as_view(),
        name="rsvp_thank",
    ),
    path(
        "rsvp/<str:rsvp_link>/partner/",
        views.RSVPPartner.as_view(),
        name="rsvp_partner",
    ),
    path(
        "details/", 
        TemplateView.as_view(template_name="weddingwrangle/wedding_details.html"),
        name="details",
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    # https://stackoverflow.com/a/63445257/3161714
    path(
        "logout/",
        LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL),
        name="logout",
    ),
]

app/weddingwrangle/models.py
from django.db import models


class Title(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Titles"


class Position(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return self.name


class RSVPStatus(models.Model):
    name = models.CharField(max_length=11)
    verbose_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "RSVP Status"
        verbose_name_plural = "RSVP Statuses"


class Dietary(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Dietaries"


class Starter(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Main(models.Model):
    name = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class Audience(models.Model):
    # M2M relationship with guests is defined within Guest class
    name = models.CharField(max_length=100)
    positions = models.ManyToManyField(Position, related_name="audience", blank=True)
    rsvp_statuses = models.ManyToManyField(RSVPStatus, related_name="audience", blank=True)

    def __str__(self):
        return self.name

class Email(models.Model):
    subject = models.CharField(max_length=100)
    text = models.CharField(max_length=10000000)
    date_sent = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
    audience = models.ForeignKey(
        Audience, 
        on_delete=models.CASCADE, 
        related_name="email", 
        null=True
    )

    def __str__(self):
        return self.subject


class Guest(models.Model):
    # Unlinked fields
    first_name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    email_address = models.CharField(max_length=50, blank=True)
    rsvp_link = models.CharField(max_length=15, verbose_name="RSVP Link")
    rsvp_qr = models.BinaryField(
        null=True, blank=True, editable=False, verbose_name="RSVP QR"
    )
    dietary_other = models.CharField(
        max_length=1000, 
        blank=True,
        verbose_name="Dietaries (other)"
    )

    # One-to-many fields
    title = models.ForeignKey(Title, on_delete=models.CASCADE, related_name="guest")
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, related_name="guest"
    )
    rsvp_status = models.ForeignKey(
        RSVPStatus,
        on_delete=models.CASCADE,
        related_name="guest",
        verbose_name="RSVP Status",
    )
    partner = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    starter = models.ForeignKey(
        Starter,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    main = models.ForeignKey(
        Main,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    # Many-to-many fields
    dietaries = models.ManyToManyField(Dietary, related_name="guest", blank=True)
    emails = models.ManyToManyField(Email, related_name="guest", blank=True)
    audiences = models.ManyToManyField(Audience, related_name="guest", blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rsvp_at = models.DateTimeField(blank=True, null=True)

    # One-to-one field
    partner = models.OneToOneField("self", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.first_name + " " + self.surname

app/weddingwrangle/views.py
import csv
from datetime import timedelta, datetime, date
from io import StringIO
import os, shutil
from plotly.offline import plot
import plotly.graph_objs as graph_objs
import re
from typing import NamedTuple
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.db.models import Min
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django_tables2 import SingleTableView
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from weddingwrangle.forms import (
    RSVPForm,
    GuestForm,
    NewEmailForm,
    RSVPEmailTemplate,
    CSVForm,
)
from weddingwrangle.models import Guest, Email
from weddingwrangle.tables import GuestTable
from qr_code.qrcode.serve import make_qr_code_url
from qr_code.qrcode.maker import QRCodeOptions, make_qr_code_image
from weddingwrangle.scripts import csv_import


class GuestList(LoginRequiredMixin, SingleTableView):
    model = Guest
    table_class = GuestTable
    template_name = "guest_list.html"


class RSVPView(UpdateView):
    model = Guest
    form_class = RSVPForm
    template_name = "weddingwrangle/rsvp.html"

    # Override get_success_url method to use the RSVP link
    def get_success_url(self):
        url = reverse_lazy("rsvp_thank", args=[self.object.rsvp_link])
        return url

    # Overriding get_object so that the RSVP link captured by the URL dispatcher is used
    # to find the object. self.kwargs is a dictionary containing captured URL parameters.
    def get_object(self):
        return self.model.objects.get(rsvp_link=self.kwargs["rsvp_link"])

    def form_valid(self, form):
        response = super().form_valid(form)
        guest = Guest.objects.get(rsvp_link=self.kwargs["rsvp_link"])
        if guest.email_address:
            email_object = Email.objects.get(subject="Thank you for RSVPing!")
            merged_message, rendered_message = generate_message(
                email_object,
                first_name=guest.first_name,
                rsvp_status=guest.rsvp_status,
                starter=guest.starter,
                main=guest.main,
                dietaries = "; ".join(
                    [dietary.name for dietary in list(guest.dietaries.all())]
                )
            )
            # https://docs.djangoproject.com/en/4.2/topics/email/
            send_mail(
                "Thank you for RSVPing!",
                message=merged_message,
                from_email=settings.FROM_EMAIL,
                recipient_list=[guest.email_address],
                fail_silently=False,
                html_message=rendered_message,
            )

        return response


class RSVPThank(DetailView):
    model = Guest
    template_name = "weddingwrangle/rsvp_thanks.html"

    def get_object(self):
        return self.model.objects.get(rsvp_link=self.kwargs["rsvp_link"])


class RSVPPartner(UpdateView):
    model = Guest
    form_class = RSVPForm
    success_url = reverse_lazy("rsvp_thank_partner")
    template_name = "weddingwrangle/rsvp_partner.html"

    # Overriding get_object so that the RSVP link captured by the URL dispatcher is used
    # to find the object. self.kwargs is a dictionary containing captured URL parameters.
    def get_object(self):
        return self.model.objects.get(rsvp_link=self.kwargs["rsvp_link"])


class GuestCreate(LoginRequiredMixin, CreateView):
    model = Guest
    form_class = GuestForm
    success_url = reverse_lazy("guest_list")
    template_name_suffix = "_create"


class GuestUpdate(LoginRequiredMixin, UpdateView):
    model = Guest
    form_class = GuestForm
    success_url = reverse_lazy("guest_list")
    template_name_suffix = "_update"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rsvp_link = self.get_object().rsvp_link
        context["qr_url"] = self.request.build_absolute_uri(
            reverse("rsvp", args=[rsvp_link])
        )
        return context


class GuestDelete(LoginRequiredMixin, DeleteView):
    model = Guest
    template_name_suffix = "_delete"
    success_url = reverse_lazy("guest_list")


# Cleaner date generation with list comprehension
def get_all_dates():
    start_date = Guest.objects.aggregate(Min("created_at"))["created_at__min"]
    days = (timezone.now() - start_date).days
    return [start_date + timedelta(days=day) for day in range(0, days + 1)]


# Load stats from database for a given date.
def load_attending_stats(date):
    # Defining a named tuple rather than multiple lists
    class AttendingStats(NamedTuple):
        date: date
        attending: int
        declined: int
        pending: int
        total: int

    # Uses less than / equal to (lte) rather than previous approach of incrementing query_date
    attending = (
        Guest.objects.filter(rsvp_at__lte=date)
        .filter(rsvp_status__name="Accepted")
        .count()
    )
    declined = (
        Guest.objects.filter(rsvp_at__lte=date)
        .filter(rsvp_status__name="Declined")
        .count()
    )
    pending = (
        Guest.objects.filter(created_at__lte=date)
        .filter(rsvp_status__name="Pending")
        .count()
    )
    total = attending + declined + pending
    return AttendingStats(date, attending, declined, pending, total)


def prepare_plot_data(attending_stats):
    """Generate plot data for home page graph"""
    # Decided to use Plotly Figure rather than Express + Dash
    # https://www.codingwithricky.com/2019/08/28/easy-django-plotly/
    # https://plotly.com/python-api-reference/generated/plotly.graph_objects.Bar.html
    # https://plotly.com/python/bar-charts/#bar-chart-with-relative-barmode

    figure = graph_objs.Figure(
        layout_title_text="Guests",
    )
    line = graph_objs.Scatter(
        name="Invited",
        x=[date.date for date in attending_stats],
        y=[date.total for date in attending_stats],
        opacity=1,
        marker_color="blue",
        mode="lines",
        hovertemplate=" %{x|%d %B %Y} <extra> %{y} guests invited </extra>",
    )
    attending_bar = graph_objs.Bar(
        name="Attending",
        x=[date.date for date in attending_stats],
        y=[date.attending for date in attending_stats],
        opacity=1,
        marker_color="green",
        hovertemplate=" %{x|%d %B %Y} <extra> %{y} attending </extra>",
    )
    declined_bar = graph_objs.Bar(
        name="Declined",
        x=[date.date for date in attending_stats],
        y=[date.declined for date in attending_stats],
        opacity=1,
        marker_color="red",
        hovertemplate=" %{x|%d %B %Y} <extra> %{y} declined </extra>",
    )
    figure.update_xaxes(
        tickformat="%d/%m",
        tickvals=[date.date for date in attending_stats],
        type="date",
    )

    figure.add_trace(line)
    figure.add_trace(attending_bar)
    figure.add_trace(declined_bar)
    figure.update_layout(barmode="relative")
    plot_div = plot(figure, output_type="div", include_plotlyjs=False)
    return plot_div


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = "weddingwrangle/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dates = get_all_dates()

        # Load named tuple into each date
        attending_stats = [load_attending_stats(date) for date in dates]
        # Put all logic into prepare_plot_data function
        context["plot_div"] = prepare_plot_data(attending_stats)
        return context


class EmailList(LoginRequiredMixin, CreateView):
    model = Email
    form_class = NewEmailForm
    template_name_suffix = "_create"

    # Retrieve list of emails
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["emails"] = Email.objects.filter(date_sent__isnull=False)
        for email in context["emails"]:
            email.count = email.guest.all().count()
        return context

    # Override get_success_url method to use the newly-created object's PK
    def get_success_url(self):
        url = reverse_lazy("email_confirm", args=[self.object.pk])
        return url


def generate_message(self, **kwargs):
    """Turn a request or unmerged message into a merged email message"""
    if hasattr(self, "object"):
        merged_message = self.object.text
    else:
        merged_message = self.text
    first_name = kwargs.get("first_name", "")
    rsvp_url = kwargs.get("rsvp_url", "")
    rsvp_url_html = kwargs.get("rsvp_url_html", "")
    rsvp_status = kwargs.get("rsvp_status", "")
    starter = kwargs.get("starter", "")
    main = kwargs.get("main", "")
    dietaries = kwargs.get("dietaries", [])
    if re.search("{{ rsvp_qr_code }}", merged_message):
        qr_options = QRCodeOptions(image_format="png", size="s")
        qr_url = make_qr_code_url(rsvp_url, qr_options)
        qr_url = self.request.build_absolute_uri(qr_url)
        merged_message = re.sub(
            "{{ rsvp_qr_code }}",
            f'<img src="{qr_url}" alt="{rsvp_url}" title="QR Code" width="200"'
            f'height="200" style="display:block">',
            merged_message,
        )
    if re.search("{{ rsvp_details }}", merged_message):
        merge_table = f"""
            <table>
                <tr>
                    <td>RSVP</td>
                    <td>{rsvp_status}</td>
                </tr>
                <tr>
                    <td>Starter</td>
                    <td>{starter}</td>

app/weddingwrangle/templates/weddingwrangle/email_create.html
{% extends "base_bootstrap.html" %}


{% load crispy_forms_tags %}
{% block content %}

  <h1> Sent emails </h1>
  <ul>

    {% for email in emails %}
      <li>{{ email.subject }} (sent {{ email.date_sent|date:"j F Y" }} to 
        <a href="{% url 'email_detail' email.id %}">{{ email.count }} guests)</a></li>

    {% empty %}
    </ul>
      Sorry - no emails have been sent yet!
    <ul>
    {% endfor %}
  </ul>

  <h1> New email </h1>

  <p>
    <form action="" method="post" id="email_form" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <a href="#" class="template-link" data-textpart="first_name">Add first name</a>
      <br>
      <a href="#" class="template-link" data-textpart="rsvp_link">Add RSVP link</a>
      <br>
      <a href="#" class="template-link" data-textpart="rsvp_qr_code">Add RSVP QR Code</a>
      <br><br>
      <input type="submit" value="Preview audience beore sending">
    </form>
  </p>
  <p>
    <em>
      By default, all emails will not be sent to declined guests, the bride or the groom 
    </em>
  </p>

  <h1> RSVP email template </h1>
  <p>
  <a href="{% url 'rsvp_email_template' %}">Click here</a> to edit the template which 
  will be sent to a guest when they fill in the RSVP form.
  </p>

  {% verbatim %}

<script>
  $(function () {
    $('.template-link').on('click', function () { 
      var textbox = $("#id_text");      
      var textpart = $(this).data('textpart');
      var startPos = textbox[0].selectionStart;
      var endPos = textbox[0].selectionEnd;
      textbox.val(textbox.val().substring(0, startPos) + "{{ " + textpart + " }}"
        + textbox.val().substring(endPos));
    });
  });

</script>
  {% endverbatim %}

{% endblock %}

app/weddingwrangle/templates/weddingwrangle/email_detail.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% load qr_code %}

{% block content %}

  <h1> Sent email: {{ object.subject }} </h1> 

  <p>
  {% if object.date_sent == None %}
    Unsent
  {% else %}
    Sent on {{ object.date_sent|date:"j F Y" }} to:
    <ul>
      {% for guest in object.audience.guest.all %} 
        {% if guest.email_address %}
          <li> 
            {{ guest.title }} {{ guest.first_name }} {{ guest.surname }} 
            ({{ guest.email_address }}): {{ guest.rsvp_status }}
          </li>
        {% endif %}
      {% endfor %}    
    </ul>
    
  {% endif %}
  </p>
    <h2> Message: </h2>
    <p>
      {{ object.text|linebreaksbr }}
    </p>

{% endblock %}

app/weddingwrangle/templates/weddingwrangle/email_rsvp_template.html
{% extends "base_bootstrap.html" %}


{% load crispy_forms_tags %}
{% block content %}

  <h1>RSVP email template</h1>

  <p>
    This template determines what is sent to each guest when they RSVP to the wedding.
  </p>

  <p>
    <form action="" method="post" id="rsvp_email_template" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <a href="#" class="template-link" data-textpart="rsvp_details">Add RSVP details</a>
      <br>
      <input type="submit" value="save">
    </form>
  </p>


  {% verbatim %}

<script>
  $(function () {
    $('.template-link').on('click', function () { 
      var textbox = $("#id_text");      
      var textpart = $(this).data('textpart');
      var startPos = textbox[0].selectionStart;
      var endPos = textbox[0].selectionEnd;
      textbox.val(textbox.val().substring(0, startPos) + "{{ " + textpart + " }}"
        + textbox.val().substring(endPos));
    });
  });

</script>
  {% endverbatim %}

{% endblock %}

app/weddingwrangle/templates/weddingwrangle/email_template.html
<html>
  <head>    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>email subject</title>
    <style>
@media only screen and (max-width: 620px) {
  table.body h1 {
    font-size: 28px !important;
    margin-bottom: 10px !important;
  }

  table.body p,
table.body ul,
table.body ol,
table.body td,
table.body span,
table.body a {
    font-size: 16px !important;
  }

  table.body .wrapper,
table.body .article {
    padding: 10px !important;
  }

  table.body .content {
    padding: 0 !important;
  }

  table.body .container {
    padding: 0 !important;
    width: 100% !important;
  }

  table.body .main {
    border-left-width: 0 !important;
    border-radius: 0 !important;
    border-right-width: 0 !important;
  }

  table.body .btn table {
    width: 100% !important;
  }

  table.body .btn a {
    width: 100% !important;
  }

  table.body .img-responsive {
    height: auto !important;
    max-width: 100% !important;
    width: auto !important;
  }
}
@media all {
  .ExternalClass {
    width: 100%;
  }

  .ExternalClass,
.ExternalClass p,
.ExternalClass span,
.ExternalClass font,
.ExternalClass td,
.ExternalClass div {
    line-height: 100%;
  }

  .apple-link a {
    color: inherit !important;
    font-family: inherit !important;
    font-size: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
    text-decoration: none !important;
  }

  #MessageViewBody a {
    color: inherit;
    text-decoration: none;
    font-size: inherit;
    font-family: inherit;
    font-weight: inherit;
    line-height: inherit;
  }

  .btn-primary table td:hover {
    background-color: #34495e !important;
  }

  .btn-primary a:hover {
    background-color: #34495e !important;
    border-color: #34495e !important;
  }
}
</style>

  </head>
   <body style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f6f6f6; width: 100%;" width="100%" bgcolor="#f6f6f6">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; max-width: 580px; padding: 10px; width: 580px; margin: 0 auto;" width="580" valign="top">
          <div class="content" style="box-sizing: border-box; display: block; margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <table role="presentation" class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; background: #ffffff; border-radius: 3px; width: 100%;" width="100%">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;" valign="top">
                  <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;" width="100%">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;">{{ email_text|linebreaksbr }}</p>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>
            <!-- END CENTERED WHITE CONTAINER -->

            <!-- START FOOTER -->
            <!-- END FOOTER -->

          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;" valign="top">&nbsp;</td>
      </tr>
    </table>
  </body>     
      
</html>

app/weddingwrangle/templates/weddingwrangle/guest_create.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}

  <h1> New guest </h1>

  <p>
    <form action="" method="post" id="guest_form" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit">
      <!-- <input type="submit" value="Cancel"> --> 
    </form>
  </p>



{% endblock %}

app/weddingwrangle/templates/weddingwrangle/guest_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
  <h1>Delete Guest</h1>

  <p>
    Are you sure you want to delete {{ object.title }} {{ object.first_name }} 
    {{ object.surname }}?
  </p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>
{% endblock %}

app/weddingwrangle/templates/weddingwrangle/guest_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1> Guests </h1>

  <br>
  <button onclick="window.location.href='{% url "guest_create" %}';" type="button" class="btn btn-primary">
    New guest
  </button>
  <button onclick="window.location.href='{% url "guest_export_csv" %}';" type="button" class="btn btn-primary">
    Export guestlist (CSV file)
  </button>
  <button onclick="window.location.href='{% url "guest_export_qr" %}';" type="button" class="btn btn-primary">
    Export QR codes (zip file)
  </button>
  <button onclick="window.location.href='{% url "guest_upload" %}';" type="button" class="btn btn-primary">
    Upload guestlist
  </button>

  {% if object_list %}
    <br><br>
    {% load render_table from django_tables2 %}
    <div class=table-respoonsive">
      {% render_table table %}
    </div>
  {% else %}
    <p>There are no guests in the database.</p>
  {% endif %}
{% endblock %}

app/weddingwrangle/templates/weddingwrangle/guest_update.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% load qr_code %}
{% block content %}

  <h1> Editing {{ guest.title }} {{ guest.first_name }} {{ guest.surname }} </h1> 

  <p>
    <form action="" method="post" id="guest_form" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" 
           onclick="window.location.href='{% url 'guest_list' %}';return false;">
    </form>
  </p>
   

    <table>
      <tr>
        <td>
          RSVP at:
        </td>
        <td>
          {{ guest.rsvp_at|date:"d F Y, P" }}
        </td>
      </tr>
      <tr>
        <td>
          RSVP link:
        </td>
        <td>
          <a href={% url 'rsvp' guest.rsvp_link %}>{{ guest.rsvp_link }}</a>
        </td>
      </tr>
      <tr>
        <td>
          RSVP QR:
        </td>
        <td>
          {% qr_from_text qr_url size="t" image_format="png" %}
        </td>
      </tr>
    </table>

  <p>
   <a href={% url 'guest_delete' guest.id %}>Delete guest</a>
  </p>

{% endblock %}

app/weddingwrangle/templates/weddingwrangle/home.html
{% extends "base_bootstrap.html" %}

{% block content %}
<head>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>

  {% autoescape off %}
    {{ plot_div }}
  {% endautoescape %}

</body>
{% endblock %}

app/weddingwrangle/templates/weddingwrangle/rsvp.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}

  <h1> RSVP for {{ guest.title }} {{ guest.first_name }} {{ guest.surname }} </h1>

  <p>
    <form action="" method="post" id="rsvp_form" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Submit">
    </form>
  </p>

{% endblock %}

app/weddingwrangle/templates/weddingwrangle/rsvp_thank_partner.html
{% extends "base_bootstrap.html" %}
{% block content %}

  <h1> Thank you for both of your responses!</h1>

  <p> We're so looking forward to seeing you on our wedding day! If you want to update
  either response, you can do so at the same link you used to get here. If you'd like
  more details about the big day, please <a href="{% url 'details' %}">click here.</a>. 
  Otherwise, feel free to close this page. </p>

{% endblock %}